version: '3.8'
services:
  system-monitor:
    image: system-monitor-system-monitor
    container_name: system-monitor
    ports:
    - 8500:80
    - 8500:80
    volumes: []
    environment:
    - NGINX_VERSION=1.29.4
    - PKG_RELEASE=1
    - DYNPKG_RELEASE=1
    - NJS_VERSION=0.9.4
    - NJS_RELEASE=1
    - ACME_VERSION=0.3.1
    deploy:
      restart_policy:
        condition: unless-stopped
    logging:
      driver: json-file
      options: {}
    networks:
    - system-monitor_webnet
